/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class ch_fhnw_ether_video_avfoundation_AVAsset_Data */

#ifndef _Included_ch_fhnw_ether_video_avfoundation_AVAsset_Data
#define _Included_ch_fhnw_ether_video_avfoundation_AVAsset_Data
#ifdef __cplusplus
extern "C" {
#endif
#ifdef __cplusplus
}
#endif
#endif
